export interface NSEStock {
  symbol: string;
  name: string;
}

export const NSE_STOCKS: NSEStock[] = [
  // Nifty 50
  { symbol: "RELIANCE.NS", name: "Reliance Industries Ltd" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services Ltd" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank Ltd" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Ltd" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank Ltd" },
  { symbol: "INFY.NS", name: "Infosys Ltd" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Ltd" },
  { symbol: "ITC.NS", name: "ITC Ltd" },
  { symbol: "LT.NS", name: "Larsen & Toubro Ltd" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank Ltd" },
  { symbol: "AXISBANK.NS", name: "Axis Bank Ltd" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance Ltd" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India Ltd" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints Ltd" },
  { symbol: "TITAN.NS", name: "Titan Company Ltd" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries Ltd" },
  { symbol: "WIPRO.NS", name: "Wipro Ltd" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement Ltd" },
  { symbol: "NESTLEIND.NS", name: "Nestle India Ltd" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies Ltd" },
  { symbol: "TECHM.NS", name: "Tech Mahindra Ltd" },
  { symbol: "MM.NS", name: "Mahindra & Mahindra Ltd" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India Ltd" },
  { symbol: "NTPC.NS", name: "NTPC Ltd" },
  { symbol: "COALINDIA.NS", name: "Coal India Ltd" },
  { symbol: "ONGC.NS", name: "Oil and Natural Gas Corporation Ltd" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation Ltd" },
  { symbol: "GRASIM.NS", name: "Grasim Industries Ltd" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel Ltd" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel Ltd" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries Ltd" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises Ltd" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports and Special Economic Zone Ltd" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto Ltd" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv Ltd" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries Ltd" },
  { symbol: "CIPLA.NS", name: "Cipla Ltd" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories Ltd" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories Ltd" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors Ltd" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company Ltd" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp Ltd" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank Ltd" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company Ltd" },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance Ltd" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors Ltd" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products Ltd" },
  { symbol: "UPL.NS", name: "UPL Ltd" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise Ltd" },
  // Nifty Next 50 + popular midcaps
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy Ltd" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power Ltd" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements Ltd" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma Ltd" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "BEL.NS", name: "Bharat Electronics Ltd" },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints India Ltd" },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals Ltd" },
  { symbol: "BIOCON.NS", name: "Biocon Ltd" },
  { symbol: "BOSCHLTD.NS", name: "Bosch Ltd" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment and Finance Company Ltd" },
  { symbol: "COLPAL.NS", name: "Colgate-Palmolive (India) Ltd" },
  { symbol: "CONCOR.NS", name: "Container Corporation of India Ltd" },
  { symbol: "DABUR.NS", name: "Dabur India Ltd" },
  { symbol: "DLF.NS", name: "DLF Ltd" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank Ltd" },
  { symbol: "GAIL.NS", name: "GAIL (India) Ltd" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products Ltd" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties Ltd" },
  { symbol: "HAVELLS.NS", name: "Havells India Ltd" },
  { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum Corporation Ltd" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life Insurance Company Ltd" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance Company Ltd" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank Ltd" },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers Ltd" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation Ltd" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering and Tourism Corporation Ltd" },
  { symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks Ltd" },
  { symbol: "LICI.NS", name: "Life Insurance Corporation of India" },
  { symbol: "LUPIN.NS", name: "Lupin Ltd" },
  { symbol: "LTIM.NS", name: "LTIMindtree Ltd" },
  { symbol: "LTTS.NS", name: "L&T Technology Services Ltd" },
  { symbol: "MPHASIS.NS", name: "Mphasis Ltd" },
  { symbol: "MRF.NS", name: "MRF Ltd" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance Ltd" },
  { symbol: "NAUKRI.NS", name: "Info Edge (India) Ltd" },
  { symbol: "NHPC.NS", name: "NHPC Ltd" },
  { symbol: "NMDC.NS", name: "NMDC Ltd" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services Software Ltd" },
  { symbol: "PAGEIND.NS", name: "Page Industries Ltd" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems Ltd" },
  { symbol: "PETRONET.NS", name: "Petronet LNG Ltd" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries Ltd" },
  { symbol: "PIIND.NS", name: "PI Industries Ltd" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "POLYCAB.NS", name: "Polycab India Ltd" },
  { symbol: "RECLTD.NS", name: "REC Ltd" },
  { symbol: "SBICARD.NS", name: "SBI Cards and Payment Services Ltd" },
  { symbol: "SIEMENS.NS", name: "Siemens Ltd" },
  { symbol: "SRF.NS", name: "SRF Ltd" },
  { symbol: "STARHEALTH.NS", name: "Star Health and Allied Insurance Company Ltd" },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals Ltd" },
  { symbol: "TATAPOWER.NS", name: "Tata Power Company Ltd" },
  { symbol: "TIINDIA.NS", name: "Tube Investments of India Ltd" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals Ltd" },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power Ltd" },
  { symbol: "TRENT.NS", name: "Trent Ltd" },
  { symbol: "VBL.NS", name: "Varun Beverages Ltd" },
  { symbol: "VEDL.NS", name: "Vedanta Ltd" },
  { symbol: "VOLTAS.NS", name: "Voltas Ltd" },
  { symbol: "ZOMATO.NS", name: "Zomato Ltd" },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences Ltd" },
  { symbol: "DALBHARAT.NS", name: "Dalmia Bharat Ltd" },
  { symbol: "UBL.NS", name: "United Breweries Ltd" },
  // IT / New-age tech
  { symbol: "PAYTM.NS", name: "One 97 Communications Ltd (Paytm)" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce Ventures Ltd (Nykaa)" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech Ltd (PolicyBazaar)" },
  { symbol: "DELHIVERY.NS", name: "Delhivery Ltd" },
  { symbol: "CARTRADE.NS", name: "CarTrade Tech Ltd" },
  // FMCG / Consumer
  { symbol: "MARICO.NS", name: "Marico Ltd" },
  { symbol: "EMAMILTD.NS", name: "Emami Ltd" },
  { symbol: "TATACOMM.NS", name: "Tata Communications Ltd" },
  { symbol: "MCDOWELL-N.NS", name: "United Spirits Ltd" },
  // Auto
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland Ltd" },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries Ltd" },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota Ltd" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries Ltd" },
  { symbol: "MGL.NS", name: "Mahanagar Gas Ltd" },
  { symbol: "MOTHERSON.NS", name: "Samvardhana Motherson International Ltd" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor Company Ltd" },
  // Banking / Finance
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank Ltd" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank Ltd" },
  { symbol: "EQUITASBNK.NS", name: "Equitas Small Finance Bank Ltd" },
  { symbol: "KARURVYSYA.NS", name: "Karur Vysya Bank Ltd" },
  { symbol: "M&MFIN.NS", name: "Mahindra & Mahindra Financial Services Ltd" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance Ltd" },
  { symbol: "PNBHOUSING.NS", name: "PNB Housing Finance Ltd" },
  { symbol: "RBLBANK.NS", name: "RBL Bank Ltd" },
  { symbol: "YESBANK.NS", name: "Yes Bank Ltd" },
  // Pharma / Healthcare
  { symbol: "ABBOTINDIA.NS", name: "Abbott India Ltd" },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories Ltd" },
  { symbol: "APOLLOMED.NS", name: "Apollo Medics International Ltd" },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare Ltd" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals Ltd" },
  { symbol: "IPCALAB.NS", name: "IPCA Laboratories Ltd" },
  { symbol: "LAURUSLABS.NS", name: "Laurus Labs Ltd" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare Institute Ltd" },
  { symbol: "NATCOPHARM.NS", name: "Natco Pharma Ltd" },
  { symbol: "SANOFI.NS", name: "Sanofi India Ltd" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals Ltd" },
  // Infrastructure / Capital Goods
  { symbol: "ABB.NS", name: "ABB India Ltd" },
  { symbol: "AIAENG.NS", name: "AIA Engineering Ltd" },
  { symbol: "CUMMINSIND.NS", name: "Cummins India Ltd" },
  { symbol: "GRINDWELL.NS", name: "Grindwell Norton Ltd" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics Ltd" },
  { symbol: "IRFC.NS", name: "Indian Railway Finance Corporation Ltd" },
  { symbol: "KEC.NS", name: "KEC International Ltd" },
  { symbol: "THERMAX.NS", name: "Thermax Ltd" },
  // Real estate
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises Ltd" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty Ltd" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates Projects Ltd" },
  { symbol: "SOBHA.NS", name: "Sobha Ltd" },
  // Chemicals / Specialty
  { symbol: "AAPL.NS", name: "Astral Ltd" },
  { symbol: "ATUL.NS", name: "Atul Ltd" },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite Ltd" },
  { symbol: "FINPIPE.NS", name: "Finolex Industries Ltd" },
  { symbol: "GNFC.NS", name: "Gujarat Narmada Valley Fertilizers & Chemicals Ltd" },
  { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine International Ltd" },
  { symbol: "VINATIORGA.NS", name: "Vinati Organics Ltd" },
  // Metals / Mining
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes Ltd" },
  { symbol: "HINDZINC.NS", name: "Hindustan Zinc Ltd" },
  { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power Ltd" },
  { symbol: "NATIONALUM.NS", name: "National Aluminium Company Ltd" },
  { symbol: "SAIL.NS", name: "Steel Authority of India Ltd" },
  { symbol: "WELCORP.NS", name: "Welspun Corp Ltd" },
  // Energy / Power
  { symbol: "ADANITRANS.NS", name: "Adani Transmission Ltd" },
  { symbol: "CESC.NS", name: "CESC Ltd" },
  { symbol: "INDIGRID.NS", name: "IndiGrid Infrastructure Investment Trust" },
  { symbol: "JSL.NS", name: "Jindal Stainless Ltd" },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi Ltd" },
];
